### ISSUE TITLE
Model crash if cpu-count > 1

### ISSUE THREAD

**Issue by plebreton** [itu-p1203/itu-p1203#10]
Hello,

On macOS with python 3.6.5, I am having some trouble with the multi-threading. For example:

`p1203-standalone examples/mode0.json --cpu-count 1` works fine (the warning aside)

> WARNING - p1203Pa - Assumed that 'aac' means 'aaclc'; please fix your input file
{
 "examples/mode0.json": {
  "O23": 5.0,
  "O34": [
   5.0,
   5.0,
   5.0,
   5.0,
   5.0,
   5.0,
   5.0,
   5.0,
   5.0,
   5.0,
   5.0,
   5.0,
   5.0,
   5.0,
   5.0,
   5.0,
   5.0,
   5.0,
   5.0,
   5.0
  ],
  "O35": 5.0,
  "O46": 4.9209299083625,
  "date": "2018-11-21T16:58:06.444516",
  "mode": 0,
  "streamId": 42
 }
}

While if the multithreading is on, like: 

`p1203-standalone examples/mode0.json --cpu-count 2` 

it crashes.

> p1203-standalone examples/mode0.json --cpu-count 2
WARNING - p1203Pa - Assumed that 'aac' means 'aaclc'; please fix your input file
objc[34951]: +[__NSPlaceholderDictionary initialize] may have been in progress in another thread when fork() was called.
objc[34951]: +[__NSPlaceholderDictionary initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
^CProcess ForkPoolWorker-2:

I am using these versions of the python modules:

> p1203-standalone       1.2.4     
pandas                 0.23.4
numpy                  1.15.3

Maybe you can easily spot where the problem is.

**Comment by slhck** [comment]
Thanks for the pointer! I can reproduce this here.

```
➜ python3 -m itu_p1203 examples/mode0.json --cpu-count 2
WARNING - p1203Pa - Assumed that 'aac' means 'aaclc'; please fix your input file
objc[27640]: +[__NSPlaceholderDictionary initialize] may have been in progress in another thread when fork() was called.
objc[27640]: +[__NSPlaceholderDictionary initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
^CProcess ForkPoolWorker-3:
Process ForkPoolWorker-2:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/werner/Documents/Projects/itu/itu-p1203/itu-p1203/itu_p1203/__main__.py", line 280, in <module>
    main()
  File "/Users/werner/Documents/Projects/itu/itu-p1203/itu-p1203/itu_p1203/__main__.py", line 260, in main
    output_results = pool.starmap(extract_from_single_file, params)
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 298, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 677, in get
Traceback (most recent call last):
    self.wait(timeout)
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 674, in wait
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 110, in worker
    task = get()
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/queues.py", line 351, in get
    with self._rlock:
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
KeyboardInterrupt
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/pool.py", line 110, in worker
    task = get()
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/queues.py", line 352, in get
    res = self._reader.recv_bytes()
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/connection.py", line 407, in _recv_by    self._event.wait(timeout)
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 552, in wait
tes
    buf = self._recv(4)
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
KeyboardInterrupt
    signaled = self._cond.wait(timeout)
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 296, in wait
    waiter.acquire()
KeyboardInterrupt
```

Seems to be solvable with:

```
OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES python3 -m itu_p1203 examples/mode0.json --cpu-count 2
```

Some explanation [here](https://blog.phusion.nl/2017/10/13/why-ruby-app-servers-break-on-macos-high-sierra-and-what-can-be-done-about-it/).

**Comment by slhck** [comment]
Given that this is something that has to do with Python and macOS High Sierra, there's nothing we can do to fix this at the moment, I think.

**Comment by plebreton** [comment]
Oh, I see. Thanks for the feedback!
