### ISSUE TITLE
pip3 installation requires numpy and scipy

### ISSUE THREAD

**Issue by derbroti** [itu-p1203/itu-p1203#2]
Minor detail:

When installing via `pip3 install .` you still need numpy and scipy as dependency:

```
hostname:~/itu-p1203# pip3 install .
Processing /root/itu-p1203
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-ms1zeocn-build/setup.py", line 3, in <module>
        import itu_p1203
      File "/tmp/pip-ms1zeocn-build/itu_p1203/__init__.py", line 3, in <module>
        from .p1203Pa import P1203Pa
      File "/tmp/pip-ms1zeocn-build/itu_p1203/p1203Pa.py", line 29, in <module>
        from . import utils
      File "/tmp/pip-ms1zeocn-build/itu_p1203/utils.py", line 30, in <module>
        import numpy as np
    ImportError: No module named 'numpy'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-ms1zeocn-build/
```

**Comment by slhck** [comment]
Thanks for the report. Should be fixed now!
