### ISSUE TITLE
Dependency error

### ISSUE THREAD

**Issue by Shivansh20128** [itu-p1203/itu-p1203#35]
Hi,
I am trying to use itu-p1203 on a Ubuntu VM. But while installing the dependencies, it is giving me an error. I have installed every dependency from the requirements.txt as well as requirements.dev.txt, but the error persists.
![image](https://github.com/itu-p1203/itu-p1203/assets/88429611/50c69475-9038-4c55-af86-9150acbbc1a1)

I have already installed the "poetry" dependency.
![image](https://github.com/itu-p1203/itu-p1203/assets/88429611/a353127b-4641-4da6-a3e4-35d7c3d20845)
 Please help me resolve this error.
 Thank You

**Comment by slhck** [comment]
Please specify which version of Ubuntu you are using.

Also, please [never install Python packages using `sudo`](https://askubuntu.com/a/802594). This is bound to break things on your system. Simply clone the repository in a folder and do `pip3 install .`. Alternatively install directly from the URL:

```
pip3 install git+https://github.com/itu-p1203/itu-p1203
```

You do not need to install the `requirements.dev.txt` dependencies, or `poetry`. These are really only needed for development.

**Comment by slhck** [comment]
PS: It seems you have not included the full error log. Please, rather than a screen shot, copy-paste the actual log contents for easier troubleshooting.

**Comment by Shivansh20128** [comment]
shivansh@ubuntu:~/Downloads$ cd itu-p1203/
shivansh@ubuntu:~/Downloads/itu-p1203$ ls
CHANGELOG.md   examples   LICENSE.md   pyproject.toml  release.sh            requirements.txt  setup.py  VERSION
DEVELOPERS.md  itu_p1203  poetry.lock  README.md       requirements.dev.txt  setup.cfg         test
shivansh@ubuntu:~/Downloads/itu-p1203$ sudo pip install .
[sudo] password for shivansh: 
Processing /home/shivansh/Downloads/itu-p1203
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /usr/lib/python3/dist-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-ixxgpuik/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'poetry>=0.12'
       cwd: None
  Complete output (151 lines):
  Traceback (most recent call last):
    File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "/usr/lib/python3/dist-packages/pip/__main__.py", line 16, in <module>
      from pip._internal.cli.main import main as _main  # isort:skip # noqa
    File "/usr/lib/python3/dist-packages/pip/_internal/cli/main.py", line 10, in <module>
      from pip._internal.cli.autocompletion import autocomplete
    File "/usr/lib/python3/dist-packages/pip/_internal/cli/autocompletion.py", line 9, in <module>
      from pip._internal.cli.main_parser import create_main_parser
    File "/usr/lib/python3/dist-packages/pip/_internal/cli/main_parser.py", line 7, in <module>
      from pip._internal.cli import cmdoptions
    File "/usr/lib/python3/dist-packages/pip/_internal/cli/cmdoptions.py", line 24, in <module>
      from pip._internal.exceptions import CommandError
    File "/usr/lib/python3/dist-packages/pip/_internal/exceptions.py", line 10, in <module>
      from pip._vendor.six import iteritems
    File "/usr/lib/python3/dist-packages/pip/_vendor/__init__.py", line 65, in <module>
      vendored("cachecontrol")
    File "/usr/lib/python3/dist-packages/pip/_vendor/__init__.py", line 36, in vendored
      __import__(modulename, globals(), locals(), level=0)
    File "<frozen importlib._bootstrap>", line 991, in _find_and_load
    File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
    File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
    File "<frozen zipimport>", line 259, in load_module
    File "/usr/share/python-wheels/CacheControl-0.12.6-py2.py3-none-any.whl/cachecontrol/__init__.py", line 9, in <module>
  
    File "<frozen importlib._bootstrap>", line 991, in _find_and_load
    File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
    File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
    File "<frozen zipimport>", line 259, in load_module
    File "/usr/share/python-wheels/CacheControl-0.12.6-py2.py3-none-any.whl/cachecontrol/wrapper.py", line 1, in <module>
    File "<frozen importlib._bootstrap>", line 991, in _find_and_load
    File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
    File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
    File "<frozen zipimport>", line 259, in load_module
    File "/usr/share/python-wheels/CacheControl-0.12.6-py2.py3-none-any.whl/cachecontrol/adapter.py", line 5, in <module>
    File "<frozen importlib._bootstrap>", line 991, in _find_and_load
    File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
    File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
    File "<frozen zipimport>", line 259, in load_module
    File "/usr/share/python-wheels/requests-2.22.0-py2.py3-none-any.whl/requests/__init__.py", line 95, in <module>
    File "<frozen importlib._bootstrap>", line 991, in _find_and_load
    File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
    File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
    File "<frozen zipimport>", line 259, in load_module
    File "/usr/share/python-wheels/urllib3-1.25.8-py2.py3-none-any.whl/urllib3/contrib/pyopenssl.py", line 46, in <module>
    File "/usr/local/lib/python3.8/dist-packages/OpenSSL/__init__.py", line 8, in <module>
      from OpenSSL import SSL, crypto
    File "/usr/local/lib/python3.8/dist-packages/OpenSSL/SSL.py", line 19, in <module>
      from OpenSSL.crypto import (
    File "/usr/local/lib/python3.8/dist-packages/OpenSSL/crypto.py", line 3263, in <module>
      utils.deprecated(
  TypeError: deprecated() got an unexpected keyword argument 'name'
  Error in sys.excepthook:
  Traceback (most recent call last):
    File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 72, in apport_excepthook
      from apport.fileutils import likely_packaged, get_recent_crashes
    File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
      from apport.report import Report
    File "/usr/lib/python3/dist-packages/apport/report.py", line 32, in <module>
      import apport.fileutils
    File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 12, in <module>
      import os, glob, subprocess, os.path, time, pwd, sys, requests_unixsocket
    File "/usr/lib/python3/dist-packages/requests_unixsocket/__init__.py", line 1, in <module>
      import requests
    File "<frozen importlib._bootstrap>", line 991, in _find_and_load
    File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
    File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
    File "<frozen zipimport>", line 259, in load_module
    File "/usr/share/python-wheels/requests-2.22.0-py2.py3-none-any.whl/requests/__init__.py", line 95, in <module>
    File "<frozen importlib._bootstrap>", line 991, in _find_and_load
    File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
    File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
    File "<frozen zipimport>", line 259, in load_module
    File "/usr/share/python-wheels/urllib3-1.25.8-py2.py3-none-any.whl/urllib3/contrib/pyopenssl.py", line 46, in <module>
    File "/usr/local/lib/python3.8/dist-packages/OpenSSL/__init__.py", line 8, in <module>
      from OpenSSL import SSL, crypto
    File "/usr/local/lib/python3.8/dist-packages/OpenSSL/SSL.py", line 19, in <module>
      from OpenSSL.crypto import (
    File "/usr/local/lib/python3.8/dist-packages/OpenSSL/crypto.py", line 3263, in <module>
      utils.deprecated(
  TypeError: deprecated() got an unexpected keyword argument 'name'
  
  Original exception was:
  Traceback (most recent call last):
    File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "/usr/lib/python3/dist-packages/pip/__main__.py", line 16, in <module>
      from pip._internal.cli.main import main as _main  # isort:skip # noqa
    File "/usr/lib/python3/dist-packages/pip/_internal/cli/main.py", line 10, in <module>
      from pip._internal.cli.autocompletion import autocomplete
    File "/usr/lib/python3/dist-packages/pip/_internal/cli/autocompletion.py", line 9, in <module>
      from pip._internal.cli.main_parser import create_main_parser
    File "/usr/lib/python3/dist-packages/pip/_internal/cli/main_parser.py", line 7, in <module>
      from pip._internal.cli import cmdoptions
    File "/usr/lib/python3/dist-packages/pip/_internal/cli/cmdoptions.py", line 24, in <module>
      from pip._internal.exceptions import CommandError
    File "/usr/lib/python3/dist-packages/pip/_internal/exceptions.py", line 10, in <module>
      from pip._vendor.six import iteritems
    File "/usr/lib/python3/dist-packages/pip/_vendor/__init__.py", line 65, in <module>
      vendored("cachecontrol")
    File "/usr/lib/python3/dist-packages/pip/_vendor/__init__.py", line 36, in vendored
      __import__(modulename, globals(), locals(), level=0)
    File "<frozen importlib._bootstrap>", line 991, in _find_and_load
    File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
    File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
    File "<frozen zipimport>", line 259, in load_module
    File "/usr/share/python-wheels/CacheControl-0.12.6-py2.py3-none-any.whl/cachecontrol/__init__.py", line 9, in <module>
  
    File "<frozen importlib._bootstrap>", line 991, in _find_and_load
    File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
    File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
    File "<frozen zipimport>", line 259, in load_module
    File "/usr/share/python-wheels/CacheControl-0.12.6-py2.py3-none-any.whl/cachecontrol/wrapper.py", line 1, in <module>
    File "<frozen importlib._bootstrap>", line 991, in _find_and_load
    File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
    File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
    File "<frozen zipimport>", line 259, in load_module
    File "/usr/share/python-wheels/CacheControl-0.12.6-py2.py3-none-any.whl/cachecontrol/adapter.py", line 5, in <module>
    File "<frozen importlib._bootstrap>", line 991, in _find_and_load
    File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
    File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
    File "<frozen zipimport>", line 259, in load_module
    File "/usr/share/python-wheels/requests-2.22.0-py2.py3-none-any.whl/requests/__init__.py", line 95, in <module>
    File "<frozen importlib._bootstrap>", line 991, in _find_and_load
    File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
    File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
    File "<frozen zipimport>", line 259, in load_module
    File "/usr/share/python-wheels/urllib3-1.25.8-py2.py3-none-any.whl/urllib3/contrib/pyopenssl.py", line 46, in <module>
    File "/usr/local/lib/python3.8/dist-packages/OpenSSL/__init__.py", line 8, in <module>
      from OpenSSL import SSL, crypto
    File "/usr/local/lib/python3.8/dist-packages/OpenSSL/SSL.py", line 19, in <module>
      from OpenSSL.crypto import (
    File "/usr/local/lib/python3.8/dist-packages/OpenSSL/crypto.py", line 3263, in <module>
      utils.deprecated(
  TypeError: deprecated() got an unexpected keyword argument 'name'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 /usr/lib/python3/dist-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-ixxgpuik/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'poetry>=0.12' Check the logs for full command output.

**Comment by Shivansh20128** [comment]
> Please specify which version of Ubuntu you are using.
> 
> Also, please [never install Python packages using `sudo`](https://askubuntu.com/a/802594). This is bound to break things on your system. Simply clone the repository in a folder and do `pip3 install .`. Alternatively install directly from the URL:
> 
> ```
> pip3 install git+https://github.com/itu-p1203/itu-p1203
> ```
> 
> You do not need to install the `requirements.dev.txt` dependencies, or `poetry`. These are really only needed for development.

The ubuntu version is 20.04.
That is what I did. I cloned the repo and did sudo pip install .
I only installed the requirements.dev.txt after I had tried other things, so I don't think that is the problem here.
Thank you

**Comment by slhck** [comment]
It looks like your entire system Python installation is broken. I would suggest starting with a new VM. This is not a bug with this project.

You may find help at askubuntu.com or superuser.com, but please make sure to follow their guidelines for asking questions.
